# Generated by Django 4.1 on 2022-08-21 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squareteroids', '0003_remove_score_hours_remove_score_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='timestamp',
        ),
    ]
